### ISSUE TITLE
Turn off Listen for ProviderWidget

### ISSUE THREAD

**Issue by FilledStacks** [FilledStacks/provider_architecture#4]
We have identified in some cases that we don't want to rebuild a widget when notifyListeners is called. This stems from the need to use a ViewModel in a widget, but that widget does not make use of the state of the ViewModel. Since the ViewModel is not using the state a rebuild is a wasted resource. 

A solution to this would be to add a construction optional parameter to the ProviderWidget called listen. This property will be a boolean with a default value true. We will then use this property in the Provider element where we use Provider.of(context) and pass the property to the listen property on the .of call.

**Comment by FilledStacks** [comment]
See Gist by Ryan [here](https://gist.github.com/chimon2000/8648acfbb71b22f7a3474339086e439c) that demonstrates the issue

**Comment by VictorUvarov** [comment]
I think you might have to create another widget for this to work. (Probably a better way) Something like `ProviderWidget.withoutListener` or something. Otherwise, if you are using `Provider.of<Model>(context, listen: false).someFunction()` you probably know you have the model above in the widget tree.

**Comment by FilledStacks** [comment]
It wouldn’t be fixed to listen false. The value will be passed in through the constructor. Only the widgets where you want to disable listening will pass listen:false to the super constructor. It’ll be true by default.
